export function createComponentsRenderer(deps) {
  const { heading, escapeHtml, statusPill, uiTextHtml, uiText } = deps;
  return function renderComponents(state) {
    const manager = state.componentManager || {};
    const records = Array.isArray(manager.records) ? manager.records : [];
    const plans = state.componentPlans || {};
    const safeId = (value) => /^[a-z][a-z0-9._-]{1,95}$/.test(String(value || "")) ? String(value) : "";
    const rows = records.map((item) => {
      const id = safeId(item.component_id);
      const type = item.component_type === "runtime" ? "runtime" : item.component_type === "model" ? "model" : "";
      if (!id || !type) return "";
      const key = `${type}:${id}`;
      const plan = plans[key];
      const bundle = plans[`bundle:${key}`];
      const reuse = plans[`reuse:${key}`];
      const imported = plans[`import:${key}`];
      const status = String(item.status || "unavailable").toLowerCase();
      const planButton = item.plan_available === false ? "" : `<button class="button button--compact" type="button" data-component-plan="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-i18n="Lập kế hoạch">${uiTextHtml("Lập kế hoạch")}</button><button class="button button--compact button--accent" type="button" data-component-bundle="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-i18n="Lập gói phụ thuộc">${uiTextHtml("Lập gói phụ thuộc")}</button>${type === "model" ? `<button class="button button--compact" type="button" data-component-native-import="${escapeHtml(id)}" data-i18n="Import từ máy này">${uiTextHtml("Import từ máy này")}</button>` : ""}`;
      const confirmButton = plan?.action ? `<button class="button button--compact button--accent" type="button" data-component-maintenance-confirm="${escapeHtml(plan.plan_id || "")}" data-i18n="Xác nhận bảo trì">${uiTextHtml("Xác nhận bảo trì")}</button>` : plan?.plan_id ? `<button class="button button--compact button--accent" type="button" data-component-confirm="${escapeHtml(plan.plan_id)}" data-i18n="Xác nhận kế hoạch">${uiTextHtml("Xác nhận kế hoạch")}</button>` : "";
      const operationHint = (value) => value?.operation_id ? `<p class="small"><strong>V8 operation:</strong> <code>${escapeHtml(value.operation_id)}</code> · ${escapeHtml(value.operation_state || "planned")}</p>` : "";
      const planDetail = plan ? `<div class="component-plan-preview" data-component-plan-preview="${escapeHtml(key)}"><div class="split"><strong><span data-i18n="Kế hoạch">${uiTextHtml("Kế hoạch")}</span> ${escapeHtml(plan.plan_id || "")}</strong>${statusPill(plan.status || "planned")}</div>${operationHint(plan)}<p>${escapeHtml(plan.reason || uiText("Kế hoạch do server quản lý; chưa thực thi."))}</p>${confirmButton}</div>` : "";
      const bundleDetail = bundle ? `<div class="component-plan-preview" data-component-bundle-preview="${escapeHtml(key)}"><div class="split"><strong><span data-i18n="Gói phụ thuộc">${uiTextHtml("Gói phụ thuộc")}</span> ${escapeHtml(bundle.plan_id || "")}</strong>${statusPill(bundle.status || "planned")}</div>${operationHint(bundle)}<p>${escapeHtml(`Các bước: ${Array.isArray(bundle.steps) ? bundle.steps.length : 0}; tải dự kiến: ${Number(bundle.download_bytes || 0)} bytes; dung lượng: ${Number(bundle.estimated_disk_bytes || 0)} bytes.`)}</p>${bundle.plan_id ? `<button class="button button--compact button--accent" type="button" data-component-bundle-confirm="${escapeHtml(bundle.plan_id)}" data-i18n="Xác nhận gói">${uiTextHtml("Xác nhận gói")}</button>` : ""}</div>` : "";
      const reuseDetail = reuse ? `<div class="component-plan-preview" data-component-reuse-preview="${escapeHtml(key)}"><div class="split"><strong><span data-i18n="Reuse bản cài sẵn">${uiTextHtml("Reuse bản cài sẵn")}</span> ${escapeHtml(reuse.plan_id || "")}</strong>${statusPill(reuse.status || "planned")}</div>${operationHint(reuse)}<p>${escapeHtml(reuse.next_action || "Chỉ ghi receipt sau khi mọi leaf khớp; không copy và không tải lại.")}</p>${reuse.plan_id ? `<button class="button button--compact" type="button" data-component-reuse-confirm="${escapeHtml(reuse.plan_id)}" data-i18n="Xác nhận đăng ký">${uiTextHtml("Xác nhận đăng ký")}</button>` : ""}</div>` : "";
      const importDetail = imported ? `<div class="component-plan-preview" data-component-import-preview="${escapeHtml(key)}"><div class="split"><strong><span data-i18n="Kế hoạch import">${uiTextHtml("Kế hoạch import")}</span> ${escapeHtml(imported.plan_id || "")}</strong>${statusPill(imported.status || "planned")}</div>${operationHint(imported)}<p>${escapeHtml(imported.next_action || "Xem xác nhận import server-owned." )}</p>${imported.plan_id ? `<button class="button button--compact button--accent" type="button" data-component-import-confirm="${escapeHtml(imported.plan_id)}" data-i18n="Xác nhận import">${uiTextHtml("Xác nhận import")}</button>` : ""}</div>` : "";
      const maintenanceButtons = `<button class="button button--compact" type="button" data-component-reuse="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-i18n="Kiểm tra bản cài sẵn">${uiTextHtml("Kiểm tra bản cài sẵn")}</button><button class="button button--compact" type="button" data-component-maintenance="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-maintenance-action="repair" data-i18n="Lập kế hoạch sửa">${uiTextHtml("Lập kế hoạch sửa")}</button><button class="button button--compact" type="button" data-component-maintenance="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-maintenance-action="update" data-i18n="Kiểm tra cập nhật">${uiTextHtml("Kiểm tra cập nhật")}</button><button class="button button--compact" type="button" data-component-maintenance="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}" data-maintenance-action="uninstall" data-i18n="Gỡ component">${uiTextHtml("Gỡ component")}</button>`;
      const sourceSlot = `<div class="component-plan-preview" data-v8-source-state="${escapeHtml(id)}" data-v8-source-type="${escapeHtml(type)}"><p class="small">Đang tải V8 source acceptance…</p></div>`;
      return `<article class="component-manager-card card" data-component-id="${escapeHtml(id)}" data-component-type="${escapeHtml(type)}"><div class="card-title-row"><div><span class="eyebrow">${escapeHtml(type.toUpperCase())}</span><h2>${escapeHtml(item.display_name || id)}</h2><p class="small">${escapeHtml(id)}</p></div>${statusPill(status)}</div><div class="component-manager-grid"><div><span data-i18n="Module state">${uiTextHtml("Module state")}</span><strong>${escapeHtml(status)}</strong></div><div><span data-i18n="Runtime state">${uiTextHtml("Runtime state")}</span><strong>${escapeHtml(item.runtime_status || "—")}</strong></div><div><span data-i18n="Model state">${uiTextHtml("Model state")}</span><strong>${escapeHtml(item.model_status || "—")}</strong></div><div><span data-i18n="Execution">${uiTextHtml("Execution")}</span><strong>${escapeHtml(item.execution || "not_run")}</strong></div></div><p>${escapeHtml(item.reason || uiText("Server snapshot chưa có thêm lý do."))}</p><div class="workspace-state__action"><strong data-i18n="Bước tiếp theo">${uiTextHtml("Bước tiếp theo")}</strong><span>${escapeHtml(item.next_action || uiText("Xem kế hoạch server-owned."))}</span></div>${sourceSlot}<div class="form-actions">${planButton}${maintenanceButtons}</div>${planDetail}${bundleDetail}${reuseDetail}${importDetail}</article>`;
    }).join("");
    const dependencyGraph = manager.dependency_graph && typeof manager.dependency_graph === "object" ? Object.keys(manager.dependency_graph).length : 0;
    const v8Panel = `<section class="card" data-v8-component-control-plane aria-live="polite"><div class="card-title-row"><div><span class="eyebrow">V8 CONTROL PLANE</span><h2>Component Operations</h2><p class="small">Opaque operation IDs, explicit confirmation và source acceptance. Không có raw filesystem path.</p></div><button class="button button--compact" type="button" data-v8-component-refresh>Làm mới V8</button></div><div data-v8-component-status class="small">Đang tải operation journal…</div><div data-v8-component-operations></div></section>`;
    return heading("MODULE MANAGER", "Components / AI Setup", "Quản lý runtime và model bằng kế hoạch server-owned. Không tự tải/cài khi mở Hub; chỉ xác nhận đúng kế hoạch đã xem.", `<button class="button" type="button" data-refresh-components data-i18n="Làm mới">${uiTextHtml("Làm mới")}</button>`) + `<div class="callout callout--warning">${escapeHtml(manager.reason || uiText("AI components là tuỳ chọn; trạng thái thiếu/partial được giữ trung thực."))} ${dependencyGraph ? `<span data-i18n="Dependency graph">${uiTextHtml("Dependency graph")}</span>: ${dependencyGraph} module.` : ""}</div>${v8Panel}<div class="component-manager-list">${rows || `<div class="empty-state"><strong data-i18n="Chưa có component catalog">${uiTextHtml("Chưa có component catalog")}</strong><span data-i18n="Catalog sẽ hiển thị khi Core bootstrap đọc được metadata tracked.">${uiTextHtml("Catalog sẽ hiển thị khi Core bootstrap đọc được metadata tracked.")}</span></div>`}</div>`;
  };
}
