export function createProjectsRenderer(deps) {
  const { heading, card, cardDynamic, field, fieldDynamic, button, escapeHtml, uiTextHtml, statusPill, workflowLibraryState, formatGb } = deps;
const creativeTabs = (state) => {
  const active = state.creativeTab || "projects";
  const tabs = [["projects", "Projects"], ["assets", "Asset Library"], ["recipes", "Prompts & Recipes"], ["compare", "Compare Board"], ["gallery", "Workflow Gallery"]];
  return `<div class="module-tabs creative-tabs" role="tablist" aria-label="Creative workspace sections">${tabs.map(([id, label]) => `<button class="tab ${active === id ? "is-selected" : ""}" type="button" role="tab" aria-selected="${active === id}" data-creative-tab="${id}">${uiTextHtml(label)}</button>`).join("")}</div>`;
};

const creativeRecovery = (recovery = {}) => {
  if (!recovery || recovery.status === "clean") return "";
  return `<section class="workspace-state creative-recovery" data-status="${escapeHtml(recovery.status)}" role="status"><div class="workspace-state__head"><div><span class="eyebrow">SAFE RECOVERY</span><h2>Workspace local cần chú ý</h2></div>${statusPill(recovery.status, recovery.status === "partial_recovery" ? "Đã phục hồi một phần" : "Cần phục hồi")}</div><p>${escapeHtml(recovery.reason || "Hub giữ nguyên local metadata chưa hợp lệ.")}</p><div class="workspace-state__action"><strong>Bước tiếp theo</strong><span>${escapeHtml(recovery.action || "Export/import lại manifest đã được validate.")}</span></div></section>`;
};

const projectOptions = (projects, selected = "", label = "Chọn project…") => `<option value="">${escapeHtml(label)}</option>${projects.map((project) => `<option value="${escapeHtml(project.id)}" ${project.id === selected ? "selected" : ""}>${escapeHtml(project.title)}${project.status === "archived" ? " · archived" : ""}</option>`).join("")}`;

const recipeOptions = (recipes, selected = "", label = "Không gắn recipe") => `<option value="">${escapeHtml(label)}</option>${recipes.map((recipe) => `<option value="${escapeHtml(recipe.id)}" ${recipe.id === selected ? "selected" : ""}>${escapeHtml(recipe.title)} · v${escapeHtml(recipe.version)}</option>`).join("")}`;

const assetThumb = (asset, extra = "") => {
  const image = asset.preview_url ? `<img src="${escapeHtml(asset.preview_url)}" alt="${escapeHtml(asset.name || asset.id)}" loading="lazy" />` : `<div class="asset-contact-sheet__placeholder" aria-hidden="true">${String(asset.media_type || "artifact").startsWith("video/") ? "▶" : String(asset.media_type || "artifact").startsWith("audio/") ? "♪" : "▧"}</div>`;
  const tags = (asset.tags || []).map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("");
  const lineage = asset.lineage?.parent_artifact_id ? `<small>Derived from ${escapeHtml(asset.lineage.parent_artifact_id)}</small>` : asset.lineage?.derived_artifact_ids?.length ? `<small>${escapeHtml(asset.lineage.derived_artifact_ids.length)} derived asset</small>` : "";
  return `<article class="asset-contact-sheet__item ${extra}" data-asset-id="${escapeHtml(asset.id)}">${image}<div class="asset-contact-sheet__copy"><strong title="${escapeHtml(asset.name || asset.id)}">${escapeHtml(asset.name || asset.id)}</strong><span>${escapeHtml(asset.media_type || "artifact")} · ${formatGb(asset.size_bytes)}</span>${lineage}<div class="tag-list">${tags}</div></div></article>`;
};

const renderCreativeProjects = (state) => {
  const creative = state.creative || {};
  const projects = creative.projects || [];
  const recent = creative.recent_projects || [];
  const selectedId = state.selectedProjectId || state.creativeProject?.project?.id || "";
  const selected = state.creativeProject?.project || projects.find((item) => item.id === selectedId);
  const exportAction = selected ? `<button class="button" type="button" data-export-project="${escapeHtml(selected.id)}">Export manifest</button>` : "";
  return `
    <div class="creative-summary"><div><strong>${projects.filter((item) => item.status === "active").length}</strong><span>project đang mở</span></div><div><strong>${creative.assets?.length || 0}</strong><span>artifact thấy được</span></div><div><strong>${creative.recipes?.length || 0}</strong><span>recipe local</span></div></div>
    ${recent.length ? `<section class="creative-recent" aria-label="Recent projects"><strong>Gần đây</strong><div>${recent.map((project) => `<button type="button" class="chip-button" data-project-open="${escapeHtml(project.id)}">${escapeHtml(project.title)}</button>`).join("")}</div></section>` : ""}
    <div class="workspace-grid workspace-grid--two">
      ${card("Tạo creative project", `<form class="stack" data-creative-form="create-project">${field("Tên project", `<input name="title" maxlength="120" required placeholder="Ví dụ: Campaign mùa thu" />`)}${field("Mô tả", `<textarea name="description" maxlength="1000" placeholder="Mục tiêu sáng tạo, audience hoặc deliverable…"></textarea>`)}${field("Tags", `<input name="tags" placeholder="campaign, social, portrait" />`)}<div class="form-actions">${button("Tạo project", "button--primary")}</div><div class="form-result" role="status"></div></form>`) }
      ${card("Mở & phục hồi", `<div class="stack">${field("Project hiện tại", `<select data-project-select>${projectOptions(projects, selectedId)}</select>`)}<p class="small">Manifest được version hóa và chỉ giữ metadata + opaque artifact ID. Hub không copy output, model, đường dẫn máy hoặc secret vào project.</p><div class="form-actions">${exportAction}</div><details class="advanced"><summary>${uiTextHtml("Import project manifest")}</summary><form class="stack creative-inline-form" data-creative-form="import-project">${field("Conflict", `<select name="conflict"><option value="copy">${uiTextHtml("Copy an toàn")}</option><option value="skip">Bỏ qua ID trùng</option><option value="replace">Thay thế ID trùng</option></select>`)}${field("Manifest JSON", `<textarea name="manifest" required rows="9" placeholder='{"contract_version":"creative-project-export.v1",…}'></textarea>`)}<div class="form-actions">${button("Validate & import")}</div><div class="form-result" role="status"></div></form></details></div>`, "", "card--flat")}
    </div>
    <section class="creative-project-grid" aria-label="Project library">${projects.map((project) => `<article class="creative-project-card ${project.id === selectedId ? "is-selected" : ""}"><div class="split"><div><span class="eyebrow">${escapeHtml(project.status)}</span><h2>${escapeHtml(project.title)}</h2></div>${statusPill(project.status === "active" ? "operational" : "partial", project.status === "active" ? "Đang làm" : "Archived")}</div><p>${escapeHtml(project.description || "Chưa có mô tả.")}</p><div class="tag-list">${(project.tags || []).map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}</div><div class="creative-project-card__meta"><span>${escapeHtml(project.asset_count)} asset</span><span>${escapeHtml(project.recipe_count)} recipe</span></div><div class="form-actions"><button class="button button--compact" type="button" data-project-open="${escapeHtml(project.id)}">Mở</button>${project.status === "active" ? `<button class="button button--compact button--danger" type="button" data-project-archive="${escapeHtml(project.id)}">${uiTextHtml("Archive")}</button>` : `<button class="button button--compact" type="button" data-project-restore="${escapeHtml(project.id)}">Khôi phục</button>`}</div></article>`).join("") || `<div class="empty-state"><strong>Chưa có project</strong><span>Tạo project đầu tiên để gom asset, recipe, workflow và compare board vào một workspace local an toàn.</span></div>`}</section>
    ${selected ? card("Project đang chọn", `<form class="stack" data-creative-form="rename-project" data-project-id="${escapeHtml(selected.id)}">${field("Tên project", `<input name="title" maxlength="120" required value="${escapeHtml(selected.title)}" />`)}${field("Mô tả", `<textarea name="description" maxlength="1000">${escapeHtml(selected.description || "")}</textarea>`)}${field("Tags", `<input name="tags" value="${escapeHtml((selected.tags || []).join(", "))}" />`)}${field("Workflow preset", `<input name="workflow_preset" value="${escapeHtml(selected.workflow_preset || "")}" placeholder="Tùy chọn, preset ID đã biết" />`)}<div class="form-actions">${button("Lưu metadata")}</div><div class="form-result" role="status"></div></form>`, "", "card--wide") : ""}`;
};

const renderCreativeAssets = (state) => {
  const creative = state.creative || {};
  const filters = state.assetFilters || {};
  const source = creative.assets || [];
  const needle = String(filters.query || "").toLowerCase();
  const tag = String(filters.tag || "").toLowerCase();
  const collections = creative.collections || [];
  const assets = source.filter((asset) => (!needle || `${asset.name || ""} ${(asset.tags || []).join(" ")}`.toLowerCase().includes(needle)) && (!tag || (asset.tags || []).includes(tag)) && (!filters.favorite || asset.favorite) && (!filters.collection || (asset.collections || []).some((item) => item.id === filters.collection)));
  const selected = state.creativeProject?.project;
  const projectAssets = state.creativeProject?.assets || [];
  return `<div class="workspace-grid workspace-grid--two">
    ${card("Tìm trong Asset Library", `<form class="stack" data-creative-form="asset-filter">${field("Tìm kiếm", `<input name="query" value="${escapeHtml(filters.query || "")}" placeholder="Tên artifact hoặc tag" />`)}${field("Tag", `<input name="tag" value="${escapeHtml(filters.tag || "")}" placeholder="Ví dụ: favorite, portrait" />`)}${field("Collection", `<select name="collection"><option value="">Tất cả collection</option>${collections.map((collection) => `<option value="${escapeHtml(collection.id)}" ${filters.collection === collection.id ? "selected" : ""}>${escapeHtml(collection.title)}</option>`).join("")}</select>`)}<label class="node-toggle"><input name="favorite" type="checkbox" ${filters.favorite ? "checked" : ""} /> Chỉ favorite</label><div class="form-actions">${button("Lọc library")}</div></form><p class="small">Contact sheet tái sử dụng artifact đã có trong Hub. Mỗi record chỉ public opaque ID và URL artifact được Hub kiểm soát.</p>`) }
    ${card("Collections", `<form class="stack" data-creative-form="create-collection">${field("Tên collection", `<input name="title" required maxlength="100" placeholder="Ví dụ: Hero candidates" />`)}${field("Tags", `<input name="tags" placeholder="portrait, final" />`)}<div class="form-actions">${button("Tạo collection")}</div><div class="form-result" role="status"></div></form><div class="creative-collection-list">${collections.map((collection) => `<span class="tag">${escapeHtml(collection.title)} · ${escapeHtml(collection.asset_count)}</span>`).join("") || "<span class=\"muted small\">Chưa có collection.</span>"}</div>`, "", "card--flat")}
  </div>
  <section class="asset-contact-sheet" aria-label="Asset contact sheet">${assets.map((asset) => `<div class="asset-library-card">${assetThumb(asset)}<div class="asset-contact-sheet__actions"><button class="button button--compact" type="button" data-asset-favorite="${escapeHtml(asset.id)}" data-next-favorite="${asset.favorite ? "false" : "true"}">${asset.favorite ? "Bỏ favorite" : "Favorite"}</button>${String(asset.media_type || "").startsWith("image/") ? `<button class="button button--compact" type="button" data-open-image-mask-studio="${escapeHtml(asset.id)}">Chỉnh sửa & Mask</button>` : ""}${selected && !projectAssets.some((item) => item.id === asset.id) ? `<button class="button button--compact" type="button" data-attach-asset="${escapeHtml(asset.id)}">Thêm vào project</button>` : ""}</div><form class="asset-tag-form" data-creative-form="asset-tags" data-asset-id="${escapeHtml(asset.id)}">${field("Tags", `<input name="tags" value="${escapeHtml((asset.tags || []).join(", "))}" aria-label="Tags for ${escapeHtml(asset.name || asset.id)}" />`)}<button class="button button--compact" type="submit">Lưu tag</button></form>${collections.length ? `<form class="asset-tag-form" data-creative-form="asset-collection" data-asset-id="${escapeHtml(asset.id)}">${field("Collection", `<select name="collection_id" aria-label="Collection for ${escapeHtml(asset.name || asset.id)}">${collections.map((collection) => `<option value="${escapeHtml(collection.id)}">${escapeHtml(collection.title)}</option>`).join("")}</select>`)}<button class="button button--compact" type="submit">Thêm collection</button></form>` : ""}</div>`).join("") || `<div class="empty-state"><strong>Không có asset phù hợp</strong><span>Upload hoặc chạy workflow hiện có để Hub đăng ký artifact, rồi quay lại đây để gắn metadata non-destructive.</span></div>`}</section>
  ${selected ? cardDynamic(`Asset của ${selected.title}`, `<div class="asset-contact-sheet asset-contact-sheet--compact">${projectAssets.map((asset) => assetThumb(asset)).join("") || `<div class="empty-state compact">Project chưa tham chiếu asset Hub nào.</div>`}</div>`, "", "card--wide") : ""}`;
};

const renderCreativeRecipes = (state) => {
  const creative = state.creative || {};
  const recipes = creative.recipes || [];
  const projects = creative.projects || [];
  const selectedId = state.selectedProjectId || state.creativeProject?.project?.id || "";
  return `<div class="workspace-grid workspace-grid--two">
    ${card("Tạo prompt & recipe", `<form class="stack" data-creative-form="create-recipe">${field("Tên recipe", `<input name="title" required maxlength="120" placeholder="Ví dụ: Cinematic portrait" />`)}${field("Prompt template", `<textarea name="prompt_template" rows="4" placeholder="A {{subject}} in a studio…"></textarea>`)}${field("Variables", `<input name="variables" placeholder="subject|Chủ thể|person|required; mood|Mood|warm" />`)}${field("Style block", `<textarea name="style_block" rows="2" placeholder="cinematic editorial lighting"></textarea>`)}${field("Negative block", `<textarea name="negative_block" rows="2" placeholder="blur, watermark"></textarea>`)}<div class="form-grid">${field("Model", `<input name="model" value="flux" />`)}${field("Seed", `<input name="seed" type="number" min="0" value="42" />`)}${field("Width", `<input name="width" type="number" min="256" value="768" />`)}${field("Height", `<input name="height" type="number" min="256" value="768" />`)}${field("Steps", `<input name="steps" type="number" min="1" value="20" />`)}</div>${field("Workflow preset", `<input name="workflow_preset" placeholder="Optional tracked preset ID" />`)}${field("Gắn project", `<select name="project_id">${projectOptions(projects, selectedId, "Không gắn project")}</select>`)}${field("Tags", `<input name="tags" placeholder="portrait, social" />`)}<div class="form-actions">${button("Lưu recipe", "button--primary")}</div><div class="form-result" role="status"></div><p class="small">Variable syntax: <code>name|Nhãn|default|required</code>. Settings được validate là JSON an toàn trước khi lưu.</p></form>`) }
    ${card("Recipe Pack", `<p class="small">Export chỉ chứa recipe/version/settings an toàn; không có model, output cá nhân, secret hoặc đường dẫn máy.</p><div class="form-actions"><button class="button" type="button" data-export-recipe-pack>Export toàn bộ recipe</button></div><details class="advanced"><summary>Import Recipe Pack</summary><form class="stack creative-inline-form" data-creative-form="import-recipe-pack">${field("Conflict", `<select name="conflict"><option value="copy">Copy an toàn</option><option value="skip">Bỏ qua ID trùng</option><option value="replace">Thay thế ID trùng</option></select>`)}${field("Pack JSON", `<textarea name="pack" required rows="9" placeholder='{"contract_version":"creative-recipe-pack.v1",…}'></textarea>`)}<div class="form-actions">${button("Validate & import")}</div><div class="form-result" role="status"></div></form></details>`, "", "card--flat")}
  </div>
  <section class="creative-recipe-grid" aria-label="Recipe library">${recipes.map((recipe) => `<article class="creative-recipe-card"><div class="split"><div><span class="eyebrow">RECIPE · v${escapeHtml(recipe.version)}</span><h2>${escapeHtml(recipe.title)}</h2></div><span class="tag">${escapeHtml(recipe.model)}</span></div><p>${escapeHtml(recipe.prompt_template || "Không có prompt template.")}</p>${recipe.style_block ? `<p class="small"><strong>Style:</strong> ${escapeHtml(recipe.style_block)}</p>` : ""}${recipe.negative_block ? `<p class="small"><strong>Negative:</strong> ${escapeHtml(recipe.negative_block)}</p>` : ""}<div class="tag-list">${(recipe.tags || []).map((tag) => `<span class="tag">${escapeHtml(tag)}</span>`).join("")}${(recipe.variables || []).map((variable) => `<span class="tag">${escapeHtml(variable.name)}</span>`).join("")}</div><form class="stack creative-inline-form" data-creative-form="apply-recipe" data-recipe-id="${escapeHtml(recipe.id)}">${(recipe.variables || []).map((variable) => fieldDynamic(variable.label || variable.name, `<input name="variable_${escapeHtml(variable.name)}" value="${escapeHtml(variable.default || "")}" ${variable.required ? "required" : ""} />`)).join("")}${field("Đích áp dụng", `<select name="target"><option value="quick">Image AI Quick</option><option value="nodes">Image Hub Nodes</option></select>`)}<div class="form-actions">${button("Áp dụng recipe")}</div><div class="form-result" role="status"></div></form></article>`).join("") || `<div class="empty-state"><strong>Chưa có recipe</strong><span>Tạo recipe để dùng lại prompt, style, negative, seed, model và settings trên Quick hoặc Node Studio.</span></div>`}</section>`;
};

const renderCreativeCompare = (state) => {
  const detail = state.creativeProject || {};
  const project = detail.project;
  const board = detail.compare || {};
  const assets = detail.assets || [];
  if (!project) return `<div class="empty-state"><strong>Chọn một project trước</strong><span>Compare Board chỉ làm việc với artifact opaque đã được project hiện tại tham chiếu.</span></div>`;
  const differences = Object.entries(board.differences || {});
  return `<div class="workspace-grid workspace-grid--two">
    ${card("Thêm artifact vào A/B board", `<form class="stack" data-creative-form="compare-add" data-project-id="${escapeHtml(project.id)}">${field("Artifact", `<select name="artifact_id">${assets.map((asset) => `<option value="${escapeHtml(asset.id)}">${escapeHtml(asset.name || asset.id)}</option>`).join("") || "<option value=\"\">Project chưa có artifact</option>"}</select>`)}${field("Nhãn", `<input name="label" maxlength="100" placeholder="A · portrait warm" />`)}<div class="form-actions">${button("Thêm vào compare")}</div><div class="form-result" role="status"></div></form><p class="small">Tối đa 8 artifact; thông tin diff chỉ chứa metadata/provenance an toàn của Hub.</p>`) }
    ${card("Lựa chọn & quay lại recipe", `<p>${board.selected_artifact_id ? `Đang chọn ${escapeHtml(board.selected_artifact_id)}` : "Chưa chọn kết quả ưu tiên."}</p><p class="small">Favorite có tính non-destructive; chọn recipe tại từng card để quay về workflow đã tạo kết quả.</p>`, "", "card--flat")}
  </div>
  <section class="compare-board" aria-label="Artifact compare board">${(board.items || []).map((item) => `<article class="compare-board__item ${item.artifact_id === board.selected_artifact_id ? "is-selected" : ""}">${assetThumb(item.asset || { id: item.artifact_id })}<div class="compare-board__body"><strong>${escapeHtml(item.label || item.artifact_id)}</strong>${item.recipe ? `<span class="small">Recipe: ${escapeHtml(item.recipe.title)} · v${escapeHtml(item.recipe.version)}</span>` : `<span class="small">Chưa có recipe liên kết</span>`}<div class="form-actions"><button class="button button--compact" type="button" data-compare-select="${escapeHtml(item.artifact_id)}" data-project-id="${escapeHtml(project.id)}">Chọn</button><button class="button button--compact" type="button" data-compare-favorite="${escapeHtml(item.artifact_id)}" data-project-id="${escapeHtml(project.id)}">Chọn + favorite</button>${item.recipe ? `<button class="button button--compact" type="button" data-apply-recipe-quick="${escapeHtml(item.recipe.id)}">Mở recipe</button>` : ""}</div></div></article>`).join("") || `<div class="empty-state"><strong>Compare Board trống</strong><span>Thêm tối thiểu hai artifact để xem khác biệt metadata, settings và provenance.</span></div>`}</section>
  ${differences.length ? card("Metadata / settings / provenance diff", `<div class="creative-diff-grid">${differences.map(([fieldName, values]) => `<details><summary>${escapeHtml(fieldName)} · ${values.length} artifact</summary><pre>${escapeHtml(JSON.stringify(values, null, 2))}</pre></details>`).join("")}</div>`, "", "card--wide") : `<div class="callout">Chưa có khác biệt metadata cần hiển thị. Compare Board sẽ cho diff khi có nhiều artifact với provenance/settings khác nhau.</div>`}`;
};

const renderCreativeGallery = (state) => {
  const creative = state.creative || {};
  const filters = state.galleryFilters || {};
  const needle = String(filters.query || "").toLowerCase();
  const category = String(filters.category || "").toLowerCase();
  const gallery = (creative.gallery || []).filter((item) => (!needle || `${item.title} ${item.description} ${(item.categories || []).join(" ")}`.toLowerCase().includes(needle)) && (!category || (item.categories || []).some((itemCategory) => String(itemCategory).toLowerCase() === category)));
  const categories = [...new Set((creative.gallery || []).flatMap((item) => item.categories || []))].sort();
  return `<div class="workspace-grid workspace-grid--two">
    ${card("Khám phá template", `<form class="stack" data-creative-form="gallery-filter">${field("Tìm kiếm", `<input name="query" value="${escapeHtml(filters.query || "")}" placeholder="Tên, mô tả hoặc category" />`)}${field("Category", `<select name="category"><option value="">Tất cả category</option>${categories.map((item) => `<option value="${escapeHtml(item)}" ${item === filters.category ? "selected" : ""}>${escapeHtml(item)}</option>`).join("")}</select>`)}<div class="form-actions">${button("Lọc gallery")}</div></form>`) }
    ${card("Capability preflight", `<p class="small">Mỗi card bên dưới đọc availability từ node registry hiện tại. Template partial/unavailable vẫn có thể được xem, nhưng Hub sẽ nêu rõ reason/action thay vì hứa backend đã chạy.</p>`, "", "card--flat")}
  </div>
  <section class="creative-gallery-grid" aria-label="Workflow template gallery">${gallery.map((item) => `<article class="creative-gallery-card"><div class="creative-gallery-card__preview" aria-hidden="true"><span>⌘</span><small>${escapeHtml(item.preview?.label || "workflow")}</small></div><div class="split"><div><span class="eyebrow">${escapeHtml(item.scope)} · ${escapeHtml(item.stage)}</span><h2>${escapeHtml(item.title)}</h2></div>${statusPill(item.status)}</div><p>${escapeHtml(item.description || "Tracked workflow template.")}</p><div class="tag-list">${(item.categories || []).map((categoryName) => `<span class="tag">${escapeHtml(categoryName)}</span>`).join("")}</div><div class="workspace-state creative-gallery-card__availability" data-status="${escapeHtml(item.status)}"><p>${escapeHtml(item.availability?.reason || "Chưa có availability detail.")}</p><div class="workspace-state__action"><strong>Bước tiếp theo</strong><span>${escapeHtml(item.availability?.action || "Mở template trong Hub Nodes.")}</span></div></div><div class="form-actions"><button class="button button--compact" type="button" data-gallery-use="${escapeHtml(item.id)}" data-gallery-scope="${escapeHtml(item.scope)}">Mở trong Hub Nodes</button><span class="small">${escapeHtml(item.node_count)} node</span></div></article>`).join("") || `<div class="empty-state"><strong>Không có template phù hợp</strong><span>Thử bỏ bớt điều kiện tìm kiếm hoặc kiểm tra workflow tracked.</span></div>`}</section>`;
};

return function renderCreativeWorkspace(state) {
  const creative = state.creative || {};
  if (state.creativeLoading && !creative.contract_version) return heading("CREATIVE WORKSPACE", "Projects & Recipes", "Đang tải metadata local an toàn từ Hub.") + `<div class="empty-state" role="status"><strong>Đang tải Creative Workspace…</strong><span>Không đọc hoặc hiển thị raw filesystem path.</span></div>`;
  const active = state.creativeTab || "projects";
  const content = workflowLibraryState(state.workflowLibrary) + (active === "assets" ? renderCreativeAssets(state) : active === "recipes" ? renderCreativeRecipes(state) : active === "compare" ? renderCreativeCompare(state) : active === "gallery" ? renderCreativeGallery(state) : renderCreativeProjects(state));
  return heading("CREATIVE WORKSPACE", "Projects, Assets & Recipes", "Tổ chức creative work theo project → artifact → recipe → workflow → compare. Local metadata được version hóa, an toàn và không đóng gói output/model/secrets.", `<button class="button" type="button" data-refresh-creative>Làm mới workspace</button>`) + creativeTabs(state) + creativeRecovery(creative.recovery) + content;
}
// Jobs implementation lives in src/ui/features/jobs/render.js.
;
}
