export function createJobsRenderer(deps) {
  const { jobRecoverySnapshot, escapeHtml, uiTextHtml, statusPill, readinessStatusLabel, artifactList, provenanceList, heading } = deps;
  return function renderJobs(state) {
    const recovery = jobRecoverySnapshot(state);
    const filter = state.jobFilter || "all";
    const filtered = recovery.records.filter((job) => filter === "all" || (filter === "active" && ["queued", "starting", "running", "cancelling"].includes(job.status)) || (filter === "attention" && ["failed", "unavailable", "cancelled", "interrupted"].includes(job.status)) || (filter === "completed" && job.status === "completed"));
    const rows = filtered.map((job) => {
      const durable = job.source === "durable";
      const active = ["queued", "starting", "running", "cancelling"].includes(job.status);
      const actions = active && !durable && job.actionId ? `<button class="button button--compact button--danger" type="button" data-focus-key="job-action-cancel" data-cancel-job="${escapeHtml(job.actionId)}">Cancel</button>` : job.resumable === true && job.actionId ? durable ? `<button class="button button--compact" type="button" data-focus-key="job-action-resume-durable" data-resume-durable-job="${escapeHtml(job.id)}">${job.status === "cancelled" ? "Resume" : "Retry"}</button>` : `<button class="button button--compact" type="button" data-focus-key="job-action-resume" data-resume-job="${escapeHtml(job.id)}">${job.status === "cancelled" ? "Resume" : "Retry"}</button>` : "";
      const timestampRows = [["Created", job.createdAt], ["Started", job.startedAt], ["Updated", job.updatedAt], ["Finished", job.finishedAt]].filter(([, value]) => value).map(([label, value]) => `<span><strong data-i18n="${escapeHtml(label)}">${uiTextHtml(label)}</strong>${escapeHtml(value)}</span>`).join("");
      const timestamps = timestampRows ? `<div class="job-timestamps">${timestampRows}</div>` : `<div class="job-timestamps"><span data-i18n="Lifecycle timestamps not published in this snapshot.">${uiTextHtml("Lifecycle timestamps not published in this snapshot.")}</span></div>`;
      const artifactSummary = job.artifacts.length ? `<div class="job-artifact-summary" data-artifact-state="available"><strong data-i18n="Artifact preview">${uiTextHtml("Artifact preview")}</strong><span>${escapeHtml(String(job.artifacts.length))} available</span></div>${artifactList(job.artifacts)}` : `<div class="job-artifact-summary" data-artifact-state="unavailable"><strong data-i18n="Artifact preview unavailable">${uiTextHtml("Artifact preview unavailable")}</strong><span data-i18n="Preview unavailable in this snapshot.">${uiTextHtml("Preview unavailable in this snapshot.")}</span></div>`;
      const recoveryReason = job.reason || "No recovery reason was published in this snapshot.";
      const lifecycle = job.lifecycle || "Not published";
      return `<article class="job-card" id="job-${escapeHtml(job.id)}" data-job-id="${escapeHtml(job.id)}" data-job-source="${escapeHtml(job.source)}" data-job-status="${escapeHtml(job.status)}" data-job-resumable="${job.resumable === true}"><div class="split"><div><div class="job-card__title"><strong>${escapeHtml(job.tool)}</strong><span class="tag job-source" data-job-source-label="${escapeHtml(job.source)}">${escapeHtml(job.sourceLabel)}</span></div><div class="row-meta">${escapeHtml(job.id)}${job.contractVersion ? ` · ${escapeHtml(job.contractVersion)}` : ""}</div></div>${statusPill(job.status, readinessStatusLabel(job.status))}</div><div class="job-lifecycle"><span data-i18n="Lifecycle">${uiTextHtml("Lifecycle")}</span><strong>${escapeHtml(lifecycle)}</strong></div><div class="progress-track" role="progressbar" aria-label="${escapeHtml(job.id)} progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${job.progress}"><div class="progress-bar" style="width:${job.progress}%"></div></div>${job.lifecycleNote ? `<p class="job-message">${escapeHtml(job.lifecycleNote)}</p>` : ""}<div class="job-recovery-detail"><div><span data-i18n="Recovery reason">${uiTextHtml("Recovery reason")}</span><p>${escapeHtml(recoveryReason)}</p></div><div><span data-i18n="Next action">${uiTextHtml("Next action")}</span><p>${escapeHtml(job.nextAction)}</p></div></div>${timestamps}${provenanceList(job.provenance)}${artifactSummary}<div class="form-actions">${actions || `<span class="job-action-note" data-i18n="No recovery action is available from this server snapshot.">${uiTextHtml("No recovery action is available from this server snapshot.")}</span>`}</div></article>`;
    }).join("");
    const filters = [["all", "All"], ["active", "Active"], ["attention", "Attention"], ["completed", "Completed"]].map(([id, label]) => `<button class="tab ${filter === id ? "is-selected" : ""}" type="button" data-focus-key="job-filter-${id}" data-job-filter="${id}" aria-pressed="${filter === id}">${label}</button>`).join("");
    const counts = recovery.counts;
    return `<section id="jobs-page" class="jobs-page" data-job-recovery-source="${escapeHtml(recovery.source)}" data-job-recovery-status="${escapeHtml(recovery.status)}">${heading("CONTROL PLANE", "Jobs", "Track server-owned queue and recovery state; actions only appear when the published record gates them.")}<div class="job-recovery-banner card"><div class="card-title-row"><div><span class="eyebrow" data-i18n="RECOVERY SNAPSHOT">${uiTextHtml("RECOVERY SNAPSHOT")}</span><h2 data-i18n="Jobs recovery">${uiTextHtml("Jobs recovery")}</h2><p>${escapeHtml(recovery.reason)}</p></div>${statusPill(recovery.status, readinessStatusLabel(recovery.status))}</div><div class="job-recovery-counts"><div><span data-i18n="Active">${uiTextHtml("Active")}</span><strong>${escapeHtml(String(counts.active))}</strong></div><div><span data-i18n="Attention">${uiTextHtml("Attention")}</span><strong>${escapeHtml(String(counts.attention))}</strong></div><div><span data-i18n="Interrupted">${uiTextHtml("Interrupted")}</span><strong>${escapeHtml(String(counts.interrupted))}</strong></div><div><span data-i18n="Recoverable">${uiTextHtml("Recoverable")}</span><strong>${escapeHtml(String(counts.recoverable))}</strong></div></div><p class="small"><span data-i18n="Source:">${uiTextHtml("Source:")}</span> ${escapeHtml(recovery.source)} · <span data-i18n="execution:">${uiTextHtml("execution:")}</span> ${escapeHtml(recovery.execution)}${recovery.dryRun ? ` · ${uiTextHtml("dry_run:")} true` : ""}</p></div><div class="module-tabs job-filters" role="group" aria-label="Job history filters">${filters}</div><div class="job-action-status" data-job-action-status role="status" aria-live="polite"></div><div class="job-list">${rows || `<div class="empty-state"><strong data-i18n="No jobs in this filter">${uiTextHtml("No jobs in this filter")}</strong><span data-i18n="Choose All to see the complete server snapshot.">${uiTextHtml("Choose All to see the complete server snapshot.")}</span></div>`}</div></section>`;
  };
}
