export function createImageAiRenderer(deps) {
  const { tool, heading, escapeHtml, formatStatus, workspaceState, imageWorkflowRail, card, field, file, button, formResult } = deps;
  function renderImageQuickV5(state) {
      const comfy = state.lifecycle?.comfyui || {};
      const imageTool = tool(state, "generate_flux");
      const recipe = state.pendingQuickRecipe || {};
      const selectedModel = recipe.model === "qwen" ? "qwen" : "flux";
      const settings = recipe.settings || {};
      const numeric = (key, fallback) => Number.isFinite(Number(settings[key])) ? Number(settings[key]) : fallback;
      const recipeNotice = state.pendingRecipeName ? `<div class="callout creative-applied-recipe" role="status"><strong>Recipe đang được áp dụng: ${escapeHtml(state.pendingRecipeName)}</strong><span>Prompt, style, negative block, seed và settings đã được đưa vào Quick. Chỉnh tiếp trước khi tạo job.</span></div>` : "";
      return heading("IMAGE", "Image AI", "Quick tạo FLUX/Qwen qua ComfyUI API ẩn. Hub Nodes dùng graph editor kéo socket; ComfyUI Advanced vẫn partial cho đến khi hoàn tất Windows WebView acceptance.", `<span class="status-pill" data-status="${escapeHtml(imageTool.tool_status || comfy.status || "stopped")}">${escapeHtml(formatStatus(imageTool.tool_status || comfy.status || "stopped"))}</span>`) + workspaceState("Image Generate / Edit", imageTool, "Chọn template Hub Nodes để nối prompt → generate/edit → upscale → preview.") + imageWorkflowRail(state) + recipeNotice + `
        <div class="workspace-grid workspace-grid--two">
          ${card("Quick", `<form data-job-form data-tool="generate_flux" data-tool-by-field="engine" data-tool-map='{"flux":"generate_flux","qwen":"generate_qwen_image"}' class="stack">${field("Model", `<select name="engine"><option value="flux" ${selectedModel === "flux" ? "selected" : ""}>FLUX.2 Klein</option><option value="qwen" ${selectedModel === "qwen" ? "selected" : ""}>Qwen Image 2512</option></select>`)}${field("Prompt", `<textarea name="prompt" required placeholder="Mô tả ảnh cần tạo…">${escapeHtml(recipe.prompt || "")}</textarea>`)}${field("Negative prompt", `<input name="negative_prompt" placeholder="Tùy chọn" value="${escapeHtml(recipe.negative_prompt || "")}" />`)}<div class="form-grid">${field("Width", `<input name="width" type="number" min="256" max="2048" step="64" value="${numeric("width", 768)}" />`)}${field("Height", `<input name="height" type="number" min="256" max="2048" step="64" value="${numeric("height", 768)}" />`)}${field("Steps", `<input name="steps" type="number" min="1" max="80" value="${numeric("steps", 20)}" />`)}${field("Seed", `<input name="seed" type="number" min="0" placeholder="random" value="${Number.isInteger(recipe.seed) ? recipe.seed : ""}" />`)}</div>${file("Input image (FLUX image-edit nếu workflow hỗ trợ)", "input_image_asset_id", "image/*")}<div class="form-actions">${button("Generate trong Hub", "button--primary")}</div>${formResult("image-result")}</form>`) }
          ${card("Chế độ làm việc", `<div class="preview-empty"><span>✦</span><strong>Không mở trình duyệt ngoài</strong><p>Chỉnh sửa & Mask giữ layer, nét brush, snapshot và provenance theo contract không phá hủy. Chọn Hub Nodes để nối typed socket bằng kéo-thả. ComfyUI Advanced là bridge partial: chỉ dùng sau checklist Windows WebView, không được coi là operational chỉ vì iframe hiển thị.</p></div><div class="form-actions"><button class="button button--primary" type="button" data-workspace-tab="image:studio">Mở Chỉnh sửa & Mask</button><button class="button" type="button" data-workspace-tab="image:nodes">Mở Hub Nodes</button><button class="button" type="button" data-workspace-tab="image:advanced">Xem ComfyUI Advanced (partial)</button></div>`, "", "card--flat")}
        </div>`;
  }
  function renderImage(state) {
      const comfy = state.lifecycle?.comfyui || {};
      const imageTool = tool(state, "generate_flux");
      return heading("IMAGE", "Image AI", "FLUX và Qwen Image gọi ComfyUI API trực tiếp. ComfyUI chạy nền ẩn khi Hub cần, không mở Local Image Studio.", `<span class="status-pill" data-status="${escapeHtml(imageTool.tool_status || comfy.status || "stopped")}">${escapeHtml(formatStatus(imageTool.tool_status || comfy.status || "stopped"))}</span>`) + workspaceState("Image Generate / Edit", imageTool, "Chọn template Hub Nodes để nối prompt → generate/edit → upscale → preview.") + `
        <div class="workspace-grid workspace-grid--two">
          ${card("Generate", `<form data-job-form data-tool="generate_flux" data-tool-by-field="engine" data-tool-map='{"flux":"generate_flux","qwen":"generate_qwen_image"}' class="stack">${field("Model", `<select name="engine"><option value="flux">FLUX.2 Klein</option><option value="qwen">Qwen Image 2512</option></select>`)}${field("Prompt", `<textarea name="prompt" required placeholder="Mô tả ảnh cần tạo…"></textarea>`)}${field("Negative prompt", `<input name="negative_prompt" placeholder="Tùy chọn" />`)}<div class="form-grid">${field("Width", `<input name="width" type="number" min="256" max="2048" step="64" value="768" />`)}${field("Height", `<input name="height" type="number" min="256" max="2048" step="64" value="768" />`)}${field("Steps", `<input name="steps" type="number" min="1" max="80" value="20" />`)}${field("Seed", `<input name="seed" type="number" min="0" placeholder="random" />`)}</div>${file("Input image (FLUX image-edit nếu workflow hỗ trợ)", "input_image_asset_id", "image/*")}<div class="form-actions">${button("Generate trong Hub", "button--primary")}</div>${formResult("image-result")}</form>`)}
          ${card("Preview & Advanced", `<div class="preview-empty"><span>✦</span><strong>Ảnh output sẽ hiện trong Jobs</strong><p>Lịch sử giữ prompt, seed, model qua metadata job an toàn; không lộ đường dẫn cục bộ.</p></div><details class="advanced"><summary>ComfyUI Advanced</summary><p>Advanced mở web interface ComfyUI trong trình duyệt nếu cần sửa workflow; normal workflow vẫn dùng form Hub ở bên trái.</p><button class="button" type="button" data-open-comfy>Open ComfyUI web interface</button></details>`, "", "card--flat")}
        </div>`;
  }
  return { renderImageQuickV5, renderImage };
}
